export const Strings1041: { [id: string]: string } = {
  "multipleDataverseLinksLabel": `((複数の関係))`,
  "UserOptions": `ユーザー オプションの設定`,
  "SelectConfig": `定義済みのコンフィグから 1 つ選択してください。選択したコンフィグはこのブラウザに保存されます。現在と異なるコンフィグを選択するとページを再ロードします。`,
  "CurrentSelection": `現在の選択`,
  "Default": `既定`,
  "ExpandedCardsLayoutWereSaved": `展開されたカードレイアウトのデータが保存されました。`,
  "ConfigWhenSaved": `保存時のコンフィグ`,
  "matchedLabel": `と一致します。`,
  "isNotMatchedWithCurrentConfigMiddle": `は、現在のコンフィグ`,
  "isNotMatchedWithCurrentConfigLast": `と一致しません。`,
  "ConfigSetErrorCheckFormat": `ConfigSet の JSON.parse() でエラーが発生しました。フォーマットを確認ください。`,
  "ExpandedCardsLayoutCanBeSavedOrApplied": `展開済みカードレイアウトを保存あるいは適用できます。`,
  "SaveCurrentExpandedCardsLayout": `現在の展開済みカードレイアウトを保存する：`,
  "ThisFunctionIsNotAvailableInSampleDemoMode": `この機能は、サンプルデモ モードでは利用できません。`,
  "PleaseInputCardsLayoutDescription": `カードレイアウトの説明を入力ください。`,
  "SaveAndClose": `保存して閉じる`,
  "ApplySavedExpandedCardsLayout": `保存済みの展開済みカードレイアウトを適用する：`,
  "NoSavedCardsLayoutForThisRecord": `このレコードに関する保存済みのカードレイアウトはありません。`,
  "Configs": `コンフィグ`,
  "CardsLayout": `カードレイアウト`,
  "CardsLayouts": `カードレイアウト`,
  "AIGeneratedContentMayBeIncorrect": `AI が生成した内容は間違っている場合があります。`,
  "SpecifyTheDistanceToBeExpandedNumerically": `展開する距離は数値で指定してください。`,
  "TheDistanceToExpandMustBeANumberGreaterThanOrEqualTo1": `展開する距離は 1 以上の数値で指定してください。`,
  "ExpandsCardsFromBegin": `「`,
  "ExpandsCardsFromMiddle": `」から、 `,
  "ExpandsCardsFromEnd": ` ステップだけカードを展開します。`,
  "ExpandsCardsFromDefaultBegin": `「`,
  "ExpandsCardsFromDefaultMiddle": `」から、既定値である `,
  "ExpandsCardsFromDefaultEnd": ` ステップだけカードを展開します。`,
  "CouldntFindTheCard": `対象となるカードを見つけられませんでした。`,
  "ChatWithAzureOpenAI": `チャット with Azure OpenAI`,
  "StartChat": `チャットを開始`,
  "ThisChatbotWillAnswerYourQuestionsAboutTheStateOfTheConnectionsYouAreViewing": `このチャットボットは、表示しているつながりの状態について、あなたのご質問にお応えします。`,
  "StopGenerating": `生成を止める`,
  "PleaseEnterYourQuestion": `質問を入力してください...`,
  "Reset": `リセット`,
  "ResetAndShowAgain": `リセットして再度表示する`,
  "CardsLayoutOfConnectionViewer": `つながりビューワーのカードレイアウト`,
  "ThisIsAConfigurationForSalesDepartment_AccountsAndContactsAsWellAsOpportunitiesAsConnectionRecords": `営業部門向けのコンフィグです。取引先企業と取引先担当者、およびつながりレコードとして営業案件が対象です。`,
  "CardsLayoutForSalesDepartment": `営業部門向けのカードレイアウト`,
  "ThisIsAConfigurationForServiceDepartment_ThisIncludesAccountsContactsAndCases": `サービス部門向けのコンフィグです。取引先企業、取引先担当者およびサポート案件が対象です。`,
  "CardsLayoutForServiceDepartment": `サービス部門向けのカードレイアウト`,
};
