export const Strings1033: { [id: string]: string } = {
  "multipleDataverseLinksLabel": `Multiple relationship`,
  "UserOptions": `User options`,
  "SelectConfig": `Select one of the predefined configurations. The selected configuration is saved in this browser. If you select a different config than the current, the page will be reloaded.`,
  "CurrentSelection": `Current selection`,
  "Default": `Default`,
  "ExpandedCardsLayoutWereSaved": `Expanded cards layout were saved.`,
  "ConfigWhenSaved": `Config when saved`,
  "matchedLabel": `is matched.`,
  "isNotMatchedWithCurrentConfigMiddle": `is not matched with current config`,
  "isNotMatchedWithCurrentConfigLast": `.`,
  "ConfigSetErrorCheckFormat": `Error in JSON.parse() in ConfigSet. Please check the format.`,
  "ExpandedCardsLayoutCanBeSavedOrApplied": `Expanded cards layout can be saved or applied.`,
  "SaveCurrentExpandedCardsLayout": `Save current expanded cards layout:`,
  "ThisFunctionIsNotAvailableInSampleDemoMode": `This function is not available in sample demo mode.`,
  "PleaseInputCardsLayoutDescription": `Please input cards layout description.`,
  "SaveAndClose": `Save and close`,
  "ApplySavedExpandedCardsLayout": `Apply saved expanded cards layout:`,
  "NoSavedCardsLayoutForThisRecord": `No saved cards layout for this record.`,
  "Configs": `Configs`,
  "CardsLayout": `Cards layout`,
  "CardsLayouts": `Cards layouts`,
  "AIGeneratedContentMayBeIncorrect": `AI-generated content may be incorrect.`,
  "SpecifyTheDistanceToBeExpandedNumerically": `Specify the distance to be expanded numerically.`,
  "TheDistanceToExpandMustBeANumberGreaterThanOrEqualTo1": `The distance to expand must be a number greater than or equal to 1.`,
  "ExpandsCardsFromBegin": `Expands cards from "`,
  "ExpandsCardsFromMiddle": `" in `,
  "ExpandsCardsFromEnd": ` steps.`,
  "ExpandsCardsFromDefaultBegin": `Expands cards from "`,
  "ExpandsCardsFromDefaultMiddle": `" in `,
  "ExpandsCardsFromDefaultEnd": ` steps as the default.`,
  "CouldntFindTheCard": `Couldn't find the card.`,
  "ChatWithAzureOpenAI": `Chat with Azure OpenAI`,
  "StartChat": `Start chat`,
  "ThisChatbotWillAnswerYourQuestionsAboutTheStateOfTheConnectionsYouAreViewing": `This chatbot will answer your questions about the state of the connections you are viewing.`,
  "StopGenerating": `Stop generating`,
  "PleaseEnterYourQuestion": `Please enter your question...`,
  "Reset": `Reset`,
  "ResetAndShowAgain": `Reset and show again`,
  "CardsLayoutOfConnectionViewer": `Cards layout of Connection Viewer`,
  "ThisIsAConfigurationForSalesDepartment_AccountsAndContactsAsWellAsOpportunitiesAsConnectionRecords": `This is a configuration for the sales department. Accounts and contacts, as well as opportunities as connection records.`,
  "CardsLayoutForSalesDepartment": `Cards layout for sales department`,
  "ThisIsAConfigurationForServiceDepartment_ThisIncludesAccountsContactsAndCases": `This is a configuration for the service department. This includes accounts, contacts, and cases.`,
  "CardsLayoutForServiceDepartment": `Cards layout for service department`,
};
